# Docs: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Angular tests

on:
  push:
    branches: [ "master", "feat/setup-github-workflow-angular-tests" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get variable infos
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ENV
          pwd
          tree

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: freservation-front
        run: npm ci

      # - run: npm run build --if-present

      - name: Run tests
        working-directory: freservation-front
        run: npm test
